name: notes
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # animations: ^2.0.2
  # animate_do: ^2.0.0
  auto_animated: ^3.0.1
  # cached_network_image: ^3.1.0+1
  # connectivity_plus: ^2.0.3
  cryptography: ^2.0.5
  # device_info_plus: ^3.1.1
  # dio: ^4.0.3
  equatable: ^2.0.3
  firebase_analytics: ^8.3.4
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^9.1.3
  # flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  # flutter_svg: ^0.23.0+1
  get: ^4.3.8
  google_fonts: ^2.1.0
  iconly: ^1.0.1
  # image_picker: ^0.8.4+4
  intl: ^0.17.0
  # modal_bottom_sheet: ^2.0.0
  # share_plus: ^3.0.4
  # package_info_plus: ^1.3.0
  # shimmer: ^2.0.0
  # permission_handler: ^8.3.0
  # photo_view: ^0.13.0
  lottie: ^1.2.1
  # local_auth: ^1.1.8
  tab_indicator_styler: ^2.0.0
  # url_launcher: ^6.0.13

dev_dependencies:
  # flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  # flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/animations/
