name: notes
description: Flutter project to save notes secure.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  animations: ^2.0.2
  auto_animated: ^3.0.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  cryptography: ^2.0.5
  device_info_plus: ^3.2.1
  equatable: ^2.0.3
  firebase_analytics: ^9.0.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_performance: ^0.8.0+4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.2
  get: ^4.6.1
  iconly: ^1.0.1
  iconsax: ^0.0.8
  intl: ^0.17.0
  local_auth: ^1.1.10
  lottie: ^1.2.1
  mask_text_input_formatter: ^2.1.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  permission_handler: ^8.3.0
  share_plus: ^3.0.4
  shimmer: ^2.0.0
  sliver_tools: ^0.2.5
  tab_indicator_styler: ^2.0.0
  url_launcher: ^6.0.18
  uuid: ^3.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/animations/
    - lib/ui/assets/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/ui/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ui/assets/launcher_icon/icon.png"
  remove_alpha_ios: true
